export const ROUTES = {
  HOME: '/(tabs)/home',
  PROGRESS: '/(tabs)/progress',
  PROFILE: '/(tabs)/profile',
  LESSON: (id: string) => `/lesson/${id}`,
  SENTENCES: (id: string) => `/sentences/${id}`,
  QUIZ: (id: string) => `/quiz/${id}`,
  REVIEW: (id: string) => `/review/${id}`,
  COMPLETE: (id: string) => `/complete/${id}`,
  GROUP_LESSON: (theme: string) => `/group-lesson/${encodeURIComponent(theme)}`,
  GROUP_REVIEW: (theme: string) => `/group-review/${encodeURIComponent(theme)}`,
  GROUP_SENTENCES: (theme: string) => `/group-sentences/${encodeURIComponent(theme)}`,
  GROUP_QUIZ: (theme: string) => `/group-quiz/${encodeURIComponent(theme)}`,
  GROUP_COMPLETE: (theme: string) => `/group-complete/${encodeURIComponent(theme)}`,
  SPLASH: '/(auth)/splash',
  WELCOME: '/(auth)/welcome',
  LOGIN: '/(auth)/login',
  SIGNUP: '/(auth)/signup',
  SIGNUP_EMAIL: '/(auth)/signup-email',
  CONFIRM_EMAIL: '/(auth)/confirm-email',
  RESET_PASSWORD: '/(auth)/reset-password',
  ONBOARDING: '/(auth)/onboarding',
  PRIVACY: '/(auth)/privacy',
  TERMS: '/(auth)/terms',
}
