export const ROUTES = {
  HOME: '/(tabs)/home',
  PROGRESS: '/(tabs)/progress',
  LEAGUES: '/(tabs)/leagues',
  PROFILE: '/(tabs)/profile',
  LESSON: (id: string) => `/lesson/${id}`,
  SENTENCES: (id: string) => `/sentences/${id}`,
  QUIZ: (id: string) => `/quiz/${id}`,
  REVIEW: (id: string) => `/review/${id}`,
  COMPLETE: (id: string) => `/complete/${id}`,
  PHONICS_PATH:    '/phonics-path',
  VOCABULARY_PATH: '/vocabulary-path',
  GROUP_LESSON: (theme: string) => `/group-lesson/${theme}`,
  GROUP_SENTENCES: (theme: string) => `/group-sentences/${theme}`,
  GROUP_QUIZ: (theme: string) => `/group-quiz/${theme}`,
  GROUP_COMPLETE: (theme: string) => `/group-complete/${theme}`,
  SPLASH: '/(auth)/splash',
  LOGIN: '/(auth)/login',
  SIGNUP: '/(auth)/signup',
  ONBOARDING: '/(auth)/onboarding',
}
